# Generated by Django 5.2.1 on 2025-06-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarSystemData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('irradiance', models.FloatField()),
                ('active_power', models.FloatField()),
            ],
            options={
                'db_table': 'solardb',
                'managed': False,
            },
        ),
    ]
