# Generated by Django 5.2.3 on 2025-06-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StringSolarData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('string_name', models.TextField()),
                ('yields', models.FloatField()),
                ('production', models.FloatField()),
            ],
            options={
                'db_table': 'strings',
                'managed': False,
            },
        ),
    ]
