# Generated by Django 5.2.3 on 2025-06-18 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_stringsolardata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StringSolarData',
        ),
    ]
