# Generated by Django 5.2.3 on 2025-06-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_delete_stringsolardata'),
    ]

    operations = [
        migrations.CreateModel(
            name='StringSolarData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yields', models.FloatField()),
                ('production', models.FloatField()),
            ],
            options={
                'db_table': 'strings',
                'managed': False,
            },
        ),
    ]
