# Generated by Django 5.2.3 on 2025-06-18 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_namestring_alter_stringsolardata_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NameString',
        ),
        migrations.DeleteModel(
            name='StringSolarData',
        ),
    ]
