# Generated by Django 5.2.3 on 2025-06-18 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_namestring_stringsolardata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NameString',
        ),
        migrations.DeleteModel(
            name='StringSolarData',
        ),
    ]
