# Generated by Django 5.2.3 on 2025-06-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_delete_namestring_delete_stringsolardata'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameString',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'string_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StringSolarData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yields', models.FloatField()),
                ('production', models.FloatField()),
            ],
            options={
                'db_table': 'string_data',
                'managed': False,
            },
        ),
    ]
